---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/profile":
    get:
      summary: Retrieves user profile information
      tags:
      - Profile
      security:
      - Bearer: []
      parameters:
      - name: Authorization
        in: header
        description: Bearer token for authorization
        schema:
          type: string
      responses:
        '200':
          description: User profile retrieved successfully
        '401':
          description: Unauthorized without token
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: localhost:3000
