name: Brakeman

on: [push, pull_request]

jobs:
  brakeman:
    name: Run Brakeman
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0.0"

      - name: Install dependencies
        run: bundle install

      - name: Run Brakeman
        run: bundle exec brakeman
